# Generated by Django 4.1.1 on 2022-09-27 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.product.models.images
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'MainFeatureType',
                'verbose_name_plural': 'MainFeatureTypes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=main.apps.product.models.images.upload_profile_images)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImagess',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubFeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'SubFeatureType',
                'verbose_name_plural': 'SubFeatureTypes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.subfeaturetype')),
            ],
            options={
                'verbose_name': 'SubFeatureValue',
                'verbose_name_plural': 'SubFeatureValues',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('definition', models.TextField()),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_without_sale', models.IntegerField(default=0)),
                ('price_in_sale', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=128)),
                ('is_sale', models.BooleanField(default=False)),
                ('is_credit_for', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('main_features', models.ManyToManyField(related_name='features', to='product.mainfeaturetype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(related_name='images', to='product.productimage')),
                ('sub_features', models.ManyToManyField(related_name='sub_features', to='product.subfeaturetype')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MainFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.mainfeaturetype')),
            ],
            options={
                'verbose_name': 'MainFeatureValue',
                'verbose_name_plural': 'MainFeatureValues',
                'ordering': ('id',),
            },
        ),
    ]
