# Generated by Django 4.1.1 on 2022-11-15 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.apps.cart.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('pictures', models.ImageField(upload_to=main.apps.cart.models.upload_profile_images)),
                ('brand_tag', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('price_for_credit', models.IntegerField(default=0)),
                ('product_number', models.IntegerField(default=1)),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CartModel',
                'verbose_name_plural': 'CartModel',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TotalCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('product_number_in_cart', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cartmodel')),
            ],
            options={
                'verbose_name': 'TotalCartModel',
                'verbose_name_plural': 'TotalCartModel',
                'ordering': ('id',),
            },
        ),
    ]
